version: '3'
services:
  api:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/go/src/github.com/yuki9541134/randish-api
    networks:
      - randish_network

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: randish_database
    ports:
      - 33065:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: randish
      TZ: 'Asia/Tokyo'
    networks:
      - randish_network

networks:
  randish_network:
    external: true
